using System.Reflection;
using EfCoreApiExample.src.DTOs;
using EfCoreApiExample.src.Entities;

namespace EfCoreApiExample.src.Extensions;

public static class EntityDtoMappingExtensions
{

    #region Customer Mappings
    public static Customer ToEntity(this CreateCustomerDto createCustomerDto)
    {
        return new()
        {
            FirstName = createCustomerDto.FirstName!,
            LastName = createCustomerDto.LastName!,
            Email = createCustomerDto.Email!,
            Address = createCustomerDto.Address!,
        };
    }

    public static Customer ToEntity(this CustomerDto customerDto)
    {
        return new()
        {
            Id = customerDto.Id,
            FirstName = customerDto.FirstName!,
            LastName = customerDto.LastName!,
            Email = customerDto.Email!,
            Address = customerDto.Address!,
        };
    }

    public static CustomerDto ToDto(this Customer customer)
    {
        return new(
            Id: customer.Id,
            FirstName: customer.FirstName,
            LastName: customer.LastName,
            Email: customer.Email,
            Address: customer.Address
        );
    }

    #endregion

    #region Product Mappings
    public static Product ToEntity(this CreateProductDto createProductDto)
    {
        return new()
        {
            Name = createProductDto.Name!,
            Price = createProductDto.Price,
        };
    }
    public static Product ToEntity(this ProductDto productDto)
    {
        return new()
        {
            Id = productDto.Id,
            Name = productDto.Name!,
            Price = (float)productDto.Price!,
        };
    }

    public static ProductDto ToDto(this Product product)
    {
        return new(
            Id: product.Id,
            Name: product.Name,
            Price: product.Price
        );
    }
    #endregion

    #region Order Mappings
    public static OrderItemDto ToDto(this OrderItem orderItem)
    {
        return new(
            Product: orderItem.Product.ToDto(),
            Quantity: orderItem.Quantity
        );
    }

    public static OrderDto ToDto(this Order order)
    {
        return new(
            Id: order.Id,
            CustomerId: order.CustomerId,
            OrderItems: order.OrderItems.Select(orderItem => orderItem.ToDto()).ToList(),
            CreatedAt: order.CreatedAt
        );
    }
    #endregion

    // update Entity field only if DTO field is not null
    // THIS WAS GENERATED BY AI
    public static TEntity ApplyNonNullValues<TEntity, TDto>(this TEntity entity, TDto dto)
        where TEntity : BaseEntity
    {
        var entityProperties = typeof(TEntity).GetProperties(BindingFlags.Public | BindingFlags.Instance)
            .Where(p => p.CanWrite && p.Name != nameof(BaseEntity.Id));

        var dtoProperties = typeof(TDto).GetProperties(BindingFlags.Public | BindingFlags.Instance)
            .ToDictionary(p => p.Name, p => p);

        foreach (var entityProp in entityProperties)
        {
            if (dtoProperties.TryGetValue(entityProp.Name, out var dtoProp))
            {
                var dtoValue = dtoProp.GetValue(dto);
                if (dtoValue is not null)
                {
                    // Handle nullable<T> to T conversion (e.g., float? -> float)
                    var targetType = Nullable.GetUnderlyingType(entityProp.PropertyType) ?? entityProp.PropertyType;
                    var convertedValue = Convert.ChangeType(dtoValue, targetType);
                    entityProp.SetValue(entity, convertedValue);
                }
            }
        }

        return entity;
    }

}